name: 'Aws testing'

# The workflow should only trigger on pull requests to the main branch
on:
  workflow_dispatch:

# Requires getting the ID Token that will be used for OIDC
permissions:
  id-token: write

jobs:
  read-dev: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::152815104156:role/sts-lab-2-target
          role-session-name: OIDCSession

      - run: aws secretsmanager get-secret-value --region us-east-1 --secret-id arn:aws:secretsmanager:us-east-1:152815104156:secret:flag_sts_lab_2-ppxzg8
        shell: bash
